import { UserProvider } from "@/context/UserContext";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import { CounterProvider } from "@/context/CounterContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <ThemeProvider>
          <CounterProvider>
            <body>{children}</body>
          </CounterProvider>
        </ThemeProvider>
      </UserProvider>
    </html>
  );
}
